services:
  portfolio:
    build: app
    labels:
      caddy: fleischer.design
      caddy.reverse_proxy: "{{upstreams 3000}}"
    env_file: .env
    restart: unless-stopped
    networks:
      - web
    volumes:
      - portfolio_data:/app/data
networks:
  web:
    external: true

volumes:
  portfolio_data: